### ISSUE TITLE
No way to toggle proxy on and off for unauthenticated proxies

### ISSUE THREAD

**Issue by willpriceb** [oh-my-fish/plugin-proxy#1]
Using `proxy` to enable the environment variables fails due to not providing a password leading to corrupted environment variables, this could possibly be solved by specifying whether the proxy is authenticated in the init of the plugin something like `set proxy_authenticated 0`. Thoughts?

**Comment by bpinto** [comment]
I think that makes sense.

What do you think @jhillyerd

**Comment by jhillyerd** [comment]
Unless I'm misunderstanding the desired result, this is already covered in the readme: you don't need to use the "proxy" command if you are on an unauthenticated proxy, the variables will be setup without user/pw info by default.

**Comment by willpriceb** [comment]
Hi James, in the situation you don't want to use the proxy, e.g. taking the
host to a different network (laptop) then I want to disable the proxy, then
come back to the proxy network I should be able to reenable the proxy

**Comment by jhillyerd** [comment]
Ah, that makes sense.  Count me in favor of the proxy_authenticated variable.

**Comment by kdiogenes** [comment]
If I understand correctly the pull request #3 solves this problem.
