### ISSUE TITLE
Add the NO_PROXY variable

### ISSUE THREAD

**Issue by blackillzone** [oh-my-fish/plugin-proxy#6]
Hi, and thanks for this plugin. Combined with auto proxy, it gets really easy to setup these settings.

And I think it would be even more good if you add the NO_PROXY variable to the possible configuration. What do you think ?

If I find some time, I'll try to do a pull request for this feature.

**Comment by jhillyerd** [comment]
I changed jobs a while ago and am no longer stuck behind a proxy server; I can't test proxy stuff anymore.

I haven't used NO_PROXY in a very long time, but I'm not sure adding it to plugin-proxy would add any value.  Having NO_PROXY set all the time shouldn't break anything as far as I know?  You could either have a `set -x NO_PROXY` in your init.fish, or just run `set -Ux NO_PROXY` from the command line once and it would persist for that user.

**Comment by blackillzone** [comment]
Okay, you're probably right on that point. I was just thinking that it would be a good idea to handle all those proxy settings in one and unique point.

But setting it in the init.fish can do the work in the most of common cases.

Thank you.

**Comment by jhillyerd** [comment]
I guess the one thing that doesn't account for is that NO_PROXY could be all caps or all lowercase, so I guess it may help to add it.  If you submit at PR, please update the example usage in the README too.  And test obviously, since I can't anymore. :)
